### ISSUE TITLE
Ideas to make .msapp files 'source code' (i.e. developer) friendly

### ISSUE THREAD

**Issue by amervitz** [microsoft/PowerApps-Language-Tooling#107]
Hello,

Having read the blog post at https://powerapps.microsoft.com/en-us/blog/source-code-files-for-canvas-apps/, I have some feedback for you to consider, in order of importance.

1. Don't build extra tools to compensate for a file format that isn't source code/git friendly to begin with. The process of packing and unpacking the .msapp files is what I consider a **legacy** concept taken from Dynamics 365/CDS/Dataverse/PowerApps/(insert your preferred technology name here) solutions. You don't need to do this! Instead, make the server-side export process for an .msapp itself place the **unpacked** file's contents directly in the .msapp file (a zip file renamed to .msapp). Then, it's just a matter of unzipping the file before editing on the local machine and saving to source control. No extra specialized tooling is then required beyond using a zip/unzip program/command already built into every OS and scripting language. If you need the files to be packed into some other format, do that yourself on the server after the .msapp file containing the unpacked files is uploaded. Don't offload the responsibility for this cumbersome process to everyone else when you can handle it yourself. Remove the barriers to adopting source control by removing unnecessary steps.
2. It seems like you're using YAML to create a domain specific language that is meant to be a less verbose data structure format than JSON or XML would be. But, you're admittedly saying in https://github.com/microsoft/PowerApps-Language-Tooling/blob/master/docs/YAMLFileFormat.md that YAML standards like escaping and comments aren't supported. All the rules and exceptions and special cases for how the file format works makes me think this isn't the right file format to use and you're twisting YAML into doing something else as a convenience to you rather than a convenience to the users who will be working with these source code files. Why don't you come up with your own DSL where everything can be expressed in the most logical syntax possible without any special rules or edge cases meant to satisfy your YAML file format rules. Work with Microsoft research or the F#/C# compiler teams to do this if the PowerApps team doesn't know how to do this themselves.
3. Make sure there is a compiler and there's IDE support with intellisense/autocomplete, go to definition, etc. Then the files can be edited with guidance and compiled/validated on a user's (i.e. developer's) local machine without wondering if what's being typed in is valid. Raw text files that can be edited by humans without any local validation is going to result in errors no matter how much guidance is provided. This is also going to be needed to deal with merging files as mentioned at https://github.com/microsoft/PowerApps-Language-Tooling#merging-changes-from-studio.
4. Last thing to add just so I can say I've said it, add support for a **real** programming language so we don't have to use expressions. I'm not as serious about this one, but this is truly what every developer who is forced to build canvas apps is thinking when they're told to build one. There are more of us than you may think. There are dozens of beautiful programming languages that people love and we could do things so much easier with them than with than expressions. Something as simple as trying to express conditional logic with expressions is way too difficult. You could use C#, JavaScript, TypeScript, Python, Ruby, and so many more, and convert them to WASM so they run on the browser. You could make the properties with expressions be function calls to a namespace and function by name with supplied parameters, and the rest of the logic exists in the source code files, and by doing so enable code reuse.

Thanks for your consideration.

Alan

**Comment by marcgerner** [comment]
Hi,

Great to have this feature! As source code management becomes more a thing nowadays, even with small businesses and small projects, this is a very helpful feature.

What I fail to understand is why you are using YAML here... The whole app is based on JSON-files and we already export the solution and store the JSON-files at this point. JSON is perfectly readable and far more accepted than YAML. 

Marc

**Comment by DTR-fforest** [comment]
Woleheartedly agree with this.
- Pack/unpack should go. In fact, we should have a viewer in an IDE like LogicApp where we can switch between the two
- YAML..?
- Intelisense, of course
- Coding PowerApps in Python? Definetly a nice bonus ^^

**Comment by Laskewitz** [comment]
Why YAML, whyyyyy?! 😭 Would love to see JSON instead...

**Comment by MikeStall** [comment]
Thanks for the discussion!

Re the original points:
1 - "why not just trivial unzip"? Fully agree. "PaSopa" (and Solution Packager) should just be an unzip.  Our take was that we could iterate far quicker with a client-side tool, more easily collect user feedback, and we could make it open source.  Our longer term plan is to push these updates into the server and make this a trivial unzip operation. 
Although we also do want to enable the rich client-side things like multiple msapps sharing the same \pkg folder, so there will be some good future discussion there.

2 - **(yaml/json/etc) - can you file a dedicated issue for that and we can have a focused discussion on that?** That deserves its own focused discussion. :) 

3- IDE support - fully agree. We just haven't built it yet. we choose to release what we had first because we believe it already offered significant value. 

4- Programming Language - The product has an existing language (https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/formula-reference), which is heavily based on Excel. We're supporting the existing product, although we may have future conversations about other languages.

**Comment by landonarogers** [comment]
Thank you everyone for your responses! We've collected your feedback and appreciate the time you've spent on improving this repo.
