### ISSUE TITLE
Errors should be written to Console.Error

### ISSUE THREAD

**Issue by BetimBeja** [microsoft/PowerApps-Language-Tooling#108]
Writing errors to `Console.Error` instead of `Console.Out` helps with logging when calling the tool from batches or from custom wrapper tools. 
I have noticed this kind of  "problematic" implementation in `SolutionPackager.exe` from [Microsoft.CrmSdk.CoreTools](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools) too.

**Comment by MikeStall** [comment]
Fixed issue with pull request #109
