### ISSUE TITLE
Handle missing parameters gracefully

### ISSUE THREAD

**Issue by scottdurow** [microsoft/PowerApps-Language-Tooling#110]
Using `pasopa -unpack` outputs the error:
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PASopa.Program.Main(String[] args) in C:\repos\PASopa\PowerApps-Language-Tooling\src\PASopa\Program.cs:line 51
```
Expected output:
```
A required argument -unpack is missing.

Usage: 
-unpack PathToApp.msapp PathToNewSourceFolder
-unpack PathToApp.msapp  // infers source folder
```

Since this will eventually make its way into SolutionPackager - maybe this isn't a priority?!

**Comment by MikeStall** [comment]
Right - pasopa is just a test harness, the way this will ship is via PowerApps CLI  and Solution Packager.

**Comment by lesaltzm** [comment]
Can't hurt to clean it up, added a PR to check args count.
