### ISSUE TITLE
Supress empty properties

### ISSUE THREAD

**Issue by scottdurow** [microsoft/PowerApps-Language-Tooling#112]
If a property is empty, then consider removing it from the pa.yaml

E.g Could **HoverFill** and **HoverBorderColor** be removed to lower verbosity?
```
        imgBox As image:
            Image: =box.img
            ImagePosition: =ImagePosition.Stretch
            X: =0
            Y: =0
            Width: =1024
            Height: =32
            HoverFill: =
            HoverBorderColor: =
            ZIndex: =1
```

**Comment by lesaltzm** [comment]
Thanks Scott!
This is an interesting point to consider. Right now, we treat a property that's missing slightly different than an empty property. A missing property means "Use the default value for this", which for Icon.HoverColor is `ColorFade(Self.Color, 20%)`, whereas an empty property is a property that the author explicitly set to empty in PowerApps Studio. Open to changing this, let me know what you think!

**Comment by scottdurow** [comment]
So if you had a value in a property (e.g. HoverFill) and you clear it - then you can never go back to it being empty again?
I think it rather comes down to the null/empty string behaviour of the control.

I can't think of any time that an empty string couldn't be treated as null for the purposes of setting properties? 
In Excel, if you clear a cell then it is treated as Empty - and not ""

**Comment by lesaltzm** [comment]
It's a bit tricky. We're trying to capture that the author explicitly set the property to Empty when it's default was non-empty. 
In Excel, this isn't an issue, since the default value for every cell is Empty. 

In our case, you would hide it by setting the property back to whatever it's original value was, in this case `ColorFade(Self.Color, 20%)`.

**Comment by scottdurow** [comment]
Understood - so if the property default was empty or "" and the value was changed by the maker - unpacked - then cleared - and unpacked again - it would remove the property from the pa.yaml?

**Comment by lesaltzm** [comment]
Yes, pretty much. The only other thing is that empty and "" are different, so 
```
        imgBox As image:
            HoverBorderColor: =
```
and
```
        imgBox As image:
            HoverBorderColor: =""
```
are different. One property is Blank(), the other is "" (empty string). Both interact with defaults the way you described in your last comment.

**Comment by scottdurow** [comment]
So the rule is if I set a property to a value that is different from the default, I'll see it in the pa.yaml - but if it's the default value then I won't see it there. Perfect!

The motivation for picking up on this was that in the SoPa, some of the XML nodes get generated even if they are empty and the default value - this makes it very verbose in source control. 

Closing this issue!
