### ISSUE TITLE
Question: Automate the download/upload of .msapp files from/into PowerApp environment

### ISSUE THREAD

**Issue by megel** [microsoft/PowerApps-Language-Tooling#119]
Is there a PowerShell cmdlet to automate the download / upload of `.msapp` files?

**Comment by scottdurow** [comment]
Once released, my understanding is that this will all happen via the solution packager and so the msapp will be exported/imported via the solution.zip

**Comment by MikeStall** [comment]
@megel - Scott is correct. This is currently just available in github. We're responding to some initial feedback from early adopters, and then we will make it available via the normal PowerPlatform ALM story:

- PowerApps CLI: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli 
- and Solution Packager:  https://docs.microsoft.com/en-us/power-platform/alm/solution-packager-tool

**Comment by lesaltzm** [comment]
I think either Get-PowerApp or Get-AdminPowerApp from https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell should help. You can download the app from the documentUri those commands return if you have the right permissions.

**Comment by megel** [comment]
@lesaltzm yes I can access the my PowerApp by `Get-PowerApp` and the result is:

![image](https://user-images.githubusercontent.com/15800069/105321740-23f86400-5bc8-11eb-8bb1-f711b8af386f.png)

Which `documentUri` do you mean - the `id` listed as internal and hwo can I download the app?

**Comment by TerhoAntila** [comment]
@megel I am not able to access the documentUri either. But one option is to use Power Automate flow to accomplish this. Use _Get App_ Action from _Power Apps for Makers (Preview)_. That will return a direct URL to the downloadable zip that actually is the msapp file. Next you can use HTTP action to GET the file from the URL and save it e.g. to your OneDrive folder with _Create file_ action.

**Comment by megel** [comment]
@TerhoAntila thanks! The flow works fine. But what is about the way back? Is there a possibility to Import the generated package by API?

**Comment by TerhoAntila** [comment]
Unfortunately that doesn't seem to be possible - I've looked into it quite extensively lately. One option might be to package the app into a Solution and deploy that (with Azure DevOps for example). Haven't tried that, thought. Yet!

https://docs.microsoft.com/en-us/power-platform/alm/solution-packager-tool

**Comment by megel** [comment]
@TerhoAntila
My conclusion after review of possible options (Flow & API) is:

A flow with GetPowerApp or GetPowerApps from the PowerApps Makers connector works fine to get the published PowerApp Packages (`msapp` format). Unfortunately, this is not as expected to support a Development Workflow where we can use the Language Tooling:

1. Download & Extract Designer App
2. Modify YAML sources
3. Pack and Upload Designer App

Because, the Download-URL PowerApp is only the Url to the published package. I see currently no chance to get the current "saved" designer PowerApp.

However, I have created a VSCode Extension to improve the workflow (download & unpack a PowerApp:
[https://github.com/megel/powerapps-helper](https://github.com/megel/powerapps-helper)

![image](https://user-images.githubusercontent.com/15800069/105629254-2d8d0080-5e42-11eb-8994-73fdd3749e69.png)

Please support me with an API to improve my tooling and get rid of the Flow workaround.

**Comment by TerhoAntila** [comment]
@megel There is also an action called List Power Apps (or similar). This will allow you to extract also non-published packages.

**Comment by TerhoAntila** [comment]
Hmm, or was it get versions or something...
