### ISSUE TITLE
Warning PA2001: Checksum mismatch. File Controls\194.json checksum does not match on extract

### ISSUE THREAD

**Issue by scottdurow** [microsoft/PowerApps-Language-Tooling#120]
What be the cause of the warning:
```
Warning PA2001: Checksum mismatch. File Controls\194.json checksum does not match on extract
```
I also get messages like the following:
```
FAIL: hash mismatch: Controls\145.json
FAIL: hash mismatch: Controls\194.json
FAIL: hash mismatch: Controls\22.json
FAIL: hash mismatch: Controls\3.json
FAIL: hash mismatch: Controls\88.json
FAIL: hash mismatch: Properties.json
FAIL: hash mismatch: References\Templates.json
FAIL!!
```

This happens on first extract where there were no existing files extracted.

**Comment by lesaltzm** [comment]
That's a warning we're using to catch cases where we aren't accurately able to roundtrip the app, it's been really useful in helping us find bugs when working on this. Can you

**Comment by lesaltzm** [comment]
That's a warning we're using to catch cases where we aren't accurately round-tripping the .msapp. If this is occuring on -unpack, can you email me with a copy of the app (my email is my github username + @microsoft.com) so I can track down what the issue is?
