### ISSUE TITLE
Checksum warnings should not be shown by default

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/PowerApps-Language-Tooling#147]
Unpacking, making a simple formula modification, and packing again should not create a checksum warning by default.  It is concerning to users who think they have done something wrong.   It is fine to have the warning under a command line switch that does the checksum comparison, or have a "packverify" version of pack that is designed specifically for this purpose, whatever is easiest - it just should not be default for "pack".

**Comment by lesaltzm** [comment]
We definitely should keep the warnings on `unpack`, that helps us catch bugs and doesn't collide with a valid user scenario.

**Comment by gregli-msft** [comment]
I have no problem with unpack and pack throwing warnings and errors if they find something unexpected, especially if it helps us catch bugs.  As you say, it is the valid user scenarios that I'd like to clean up.

**Comment by MikeStall** [comment]
I think the distinction here is when the warning comes from our automatic "repackage after unpack to verify it worked" ... any checksum mismatch from that step is a bug.
