### ISSUE TITLE
Error   PA3002: Format is not supported. Can't find CanvasManifest.json file - is sources an old version?

### ISSUE THREAD

**Issue by westerdaled** [microsoft/PowerApps-Language-Tooling#150]
A week ago 

- Cloned the repo ,` build ci` 
- Downloaded and unpacked our 'App (Production).msapp'
- I successfully edited the source and remove an erronous sql  connection
- packed the app and opened it in our production environment, to check an annoying error "need to share the SQL Server connection " has gone.
- It had , so happy days!

Today I thought I would repeat the process  and document what I did but hit the issue below. Now this  is weird as nothing has changed incl the file I downloaded last week ( before any edits) , I am even using the same commands as found in my  Ps7 windows terminal, command history.

![PASopa issue](https://user-images.githubusercontent.com/937208/107528785-1ecc7a80-6bb2-11eb-84d3-4f1e2feac033.PNG)
 
Things i have tried ... 
I have pulled the latest source and rebuilt so now using 0.18 of the converter.

**Comment by lesaltzm** [comment]
Hi Daniel, thanks for bringing this up. That definitely shouldn't be happening. When unpacking an app, we immediately try to repack it as well, just to ensure that nothing went wrong in the unpack process. It looks like that's failing here.

Can you check what actually got added to `C:\dev\Clients\AnyClient\powerappsrc\`, since the unpack should have been successful? Is there a CanvasManifest.json file there?

**Comment by westerdaled** [comment]
Hi McCall

Thanks for looking into this. 
Yes it seems have unpacked correctly, as CanvasManifest.json  is in ` C:\dev\Clients\AnyClient\powerappsrc\.`

**Comment by lesaltzm** [comment]
Thanks! I'm able to reproduce it. It looks like we have a small bug when building the path for that repack step. As a workaround, if you run the command without that last `\` in the target folder path, you shouldn't see the error.

**Comment by westerdaled** [comment]
Cool . That is much better😀, I can get on with my documentation.
![PASopa without the trailing slash](https://user-images.githubusercontent.com/937208/107571306-a631e200-6be2-11eb-86d0-ff0ebe7869ea.PNG)
