### ISSUE TITLE
PA3001: Internal error. Can't unescape path

### ISSUE THREAD

**Issue by RobertR21** [microsoft/PowerApps-Language-Tooling#153]
Received the following error when using `pasopa -pack`:

`PA3001: Internal error. Can't unescape path: DataSources\JourneyPlanner|Sendforapproval.json`
Note that in the actual DataSource folder, the file is named "JourneyPlanner%7cSendforapproval.json"

"JourneyPlanner|Sendforapproval.json" is in refernce to a Power Automate flow that's associated with the Canvas App I'm trying to pack.  If I had to guess, I suspect that this error is thrown due to the name of the flow including that pipe charachter.

**Comment by MikeStall** [comment]
@RobertR21 - does this repro on the latest build? We had a recent fix that might address this. 
If it still repos, is it possible for you to share your .msapp file with me? You can send it to jmstall at microsoft dot com.

**Comment by RobertR21** [comment]
Hi @MikeStall - I think I used the latest build. I just cloned/opened it with github desktop yesterday (11th of Feb 2021).

Happy to send a msapp file that reproduces this as well, just need to create an anonimised version because the comments/datasources of the app might reference some potentially sensitive information regarding the client I'm working for..

**Comment by mdocter** [comment]
I'm using the latest version and I have the same error when a Screen name contains a dash (-).
For example `my-screen` is unpacked as `my%2dscreen.pa.yml` and afterwards fails to pack with this error.

The utitlity `DontEscapeChar` method is maybe a bit to restrictive?

https://github.com/microsoft/PowerApps-Language-Tooling/blob/739698182d830fc3370590e3141c830b2fdd81c1/src/PAModel/Utility/Utility.cs#L202-L215

Normally dashes are allowed in file names.

**Comment by MikeStall** [comment]
@mdocter - thanks for the tip ... that helped me create a repro!

Re `DontEscapeChar` ... it should be ok to do extra escaping (in theory, we could fully escape everything). The reason not to escape is readability. Although we could avoid escaping '-' to preserve readability, but it's not a correctness issue. 
For example, we need to run on multiple operating systems, so the file escaping rules can't be too closely tied to just windows.

**Comment by MikeStall** [comment]
The problem is we're double unescaping the path. 
Utility.GetRelativePath unescapes, so this snippet double unescapes:

```
            var entries = from fullPath in fullPaths
                          let relativePath = Utility.GetRelativePath(fullPath, root)
                          select new Entry(fullPath)
                          {
                              _relativeName = Utility.UnEscapeFilename(relativePath),
                              Kind = FileEntry.TriageKind(relativePath)
                          };
```
