### ISSUE TITLE
URI Format Error During Unpack When Using Relative Pathnames

### ISSUE THREAD

**Issue by jack-work** [microsoft/PowerApps-Language-Tooling#162]
Error when using relative pathnames.  Reproducible in PowerShell and ConEmu.  Uncertain whether or not this affects the output content.

Error   PA3001: Internal error. Invalid URI: The format of the URI could not be determined.
![image](https://user-images.githubusercontent.com/62115878/108787835-6b597380-752b-11eb-8090-d1aa6a5b79ad.png)

**Comment by MikeStall** [comment]
Possible dup of #156? 
Are you synced on latest? Current bits should be normalizing relative paths to full names.

**Comment by MikeStall** [comment]
Closing as fixed, duplicated of #156, which was recently fixed.
