### ISSUE TITLE
PA3005 Validation Error

### ISSUE THREAD

**Issue by bli585** [microsoft/PowerApps-Language-Tooling#184]
Saving out an app of ours to a msapp file and attempting to run:

pasopa -unpack "*edited out paths for post*\MSAPP\Billing Management System.msapp" "*edited out paths for post*\MSAPP\src"

There is a live version of this app that is used daily by multiple users.

A warning and an error received, below. No files generated in src folder.

Warning PA2001: Checksum mismatch. Checksum doesn't match on extract.
Error PA3005: Validation error: Unable to find TestStepsMetadata property for TestCase *I edited a GUID out for this post, not sure if this is needed to diagnose*

Opening 'Billing Management System.msapp' with 7zip, I can find the GUID from the error in a file - AppTests folder on the top level contains a single file called '2.json'. Every ID in this file points at a varying page under microsoft.com/appmagic/[varying page]. Examples of varying page are 'testsuite' or 'testcase'. None of these pages go anywhere when the URL is entered into a browser.

Tried redownloading the msapp, and tried from multiple locations, same issue.

**Comment by lesaltzm** [comment]
That looks like a bug with the Test Studio experimental feature from the editor. They should always be writing out a TestStepsMetadata property. Would you be willing to email your app or at least the 2.json file to me (lesaltzm@microsoft.com) so I can look into this further. 

Also, if you open the test studio for that app, is there anything odd? A screenshot of that would also be appreciated.

**Comment by bli585** [comment]
Emailed the JSON file and a screenshot over!

**Comment by lesaltzm** [comment]
From @CarlosFigueiraMSFT's investigation

> It is possible for a test case not to have the TestStepsMetadata property – if it is a brand new case. The scenario is if the maker opens test studio, adds a new test case, and does not add any test steps to it: that will create a test case with no metadata property. Only when the first step is added to the test case is that that property will be created.
> 
> And that empty test suite / test case that you see when you open test studio for the first time is actually by design – if the app does not have any test cases, the first time Test Studio is opened, we will create a new test suite containing a new (empty) test case.
> 
> For this specific app, it seems like they might have opened Test Studio once (so that the “shell” test suite/case were created) but never used it.
>

**Comment by lesaltzm** [comment]
This appears to be a bug in our tool, we'll address it. In the mean time, to unblock yourself, you can probably just delete that AppTests folder when you have the .msapp open in 7zip.
