### ISSUE TITLE
"PA3002: Format is not supported. Can't find CanvasManifest.json file - is sources an old version?"

### ISSUE THREAD

**Issue by swerver32** [microsoft/PowerApps-Language-Tooling#185]
I have a new powerapp that started with 1 home screen.  Then 2 different devs took copies and made a couple new screens each.  Now we want to merge these back into 1 app.  I can unpack and pack both apps individually.  When I copied the second on to the first in an attempt to merge them, I now get the error in the subject header, when I try to pack the new merged folder.  The file CanvasManifest.json is there in the same place as always.  I am looking at the diff between the 2 sets of source code and I can see all the screens and connections are there but seems like some of the files are a little jumbled, like CanvasManifest.json, Connections.json, ControlTemplates.json.  

What can I do to make this merge work?  Is there a specific change to make or to ignore?  Is anybody able to use this in this way yet?  My goal would be to be able to branch from and merge to a master version of the app just like we would with a more traditional coding platform to allow continuous integration.

**Comment by MikeStall** [comment]
Be sure they both are on the latest format (exported by the latest build of the tool). 
You should be able to merge them via git or any 3-way merge just like you'd do with a normal code. 

Delete the \entropy directory - this will have lots of conflicts, but this directory is optional.

**Comment by MikeStall** [comment]
@swerver32 - do the instructions here help in your scenario?

**Comment by swerver32** [comment]
I ended up abandoning that .msapp and tried again with the latest version, had better luck with that one.  Still didn't figure out what was wrong with the old one.  It seems like if there are too many new screens, connections, etc then the merge doesn't work as well as a merge of apps that are not adding those things.
