### ISSUE TITLE
Application Insights Instrumentation Key needs to be handled separately

### ISSUE THREAD

**Issue by pratapladhani** [microsoft/PowerApps-Language-Tooling#189]
Power Apps Canvas apps allow adding an Application Insights instrumentation key as per [this article](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/application-insights).

After unpacking, currently this Instrumentation Key is part of the CanvasManifest.json file as part of the Properties Array. It would be great to have this Instrumentation Key pulled out as a separate file, so that it can be easily changed as part of the ALM CI/CD pipelines. 

![image](https://user-images.githubusercontent.com/2510704/111831915-45668b00-88ad-11eb-830e-aec9011c9cae.png)

**Comment by MikeStall** [comment]
More on PowerApps and AppInsights:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/application-insights
