### ISSUE TITLE
Issue using the `pack` command when the directory being packed includes a period (.) in its name

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/PowerApps-Language-Tooling#202]
The logic in the `Utilities.AppendDirectorySeparatorChar` [here](https://github.com/microsoft/PowerApps-Language-Tooling/blob/c443fc7823c25d91e9f653aef6236095299382f5/src/PAModel/Utility/Utilities.cs#L173-L183) does not consider directories that include a period (.) in their names, ie "C:\SomePath\SomeSolution\SomeSolution.SomeProject"

Since the `Path.HasExtension` method returns `true` in this instance, the `Path.DirectorySeparatorChar` will not be appended.

**Comment by MikeStall** [comment]
The root problem here is that we want to call Path.GetRelativePath(), but that's not available in our framework, so we have a hand rolled implementation, and that implementation has bugs. 

The latest official  implementation is at: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L861

(but that impl is very complex with lots of helpers, OS-specific code, unsafe pointers, etc)

**Comment by MikeStall** [comment]
resolved with #204
