### ISSUE TITLE
The build failed.

### ISSUE THREAD

**Issue by msjammu** [microsoft/PowerApps-Language-Tooling#205]
1. Install .NET Core SDK 3.1.x (x64).
2. Clone the repo at https://github.com/microsoft/PowerApps-Language-Tooling
3. Run build.cmd in the root directory.

build failed. Ideas?

E:\Git\PASopa\PowerApps-Language-Tooling>build
C:\Program Files\dotnet\sdk\3.1.408\NuGet.targets(128,5): error : Unable to load the service index for source https://msazure.pkgs.visualstudio.com/_packaging/Official/nuget/v3/index.json. [E:\Git\PASopa\PowerApps-Language-Tooling\targets\targets.csproj]
C:\Program Files\dotnet\sdk\3.1.408\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized). [E:\Git\PASopa\PowerApps-Language-Tooling\targets\targets.csproj]

The build failed. Fix the build errors and run again.

**Comment by MikeStall** [comment]
It looks like you have some global nuget configuration that's adding private feeds. 
See the 401 and the reference to nuget dependency https://msazure.pkgs.visualstudio.com/_packaging/Official/nuget/v3/index.json?

**Comment by lesaltzm** [comment]
Issue is stale, closing. Reactivate if you resolved the nuget config issue and are still having this problem.
