### ISSUE TITLE
Server side changes to improve .msapp format.

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Language-Tooling#21]
Improve the real .msapp format to make conversions easier. 

As general principles:
- avoid double json encoding because that breaks checksums. 
- separate out volatile information (timestamps, per-environment) from stable information. 
- remove fields that are redundant or don't need to be emitted. 

Some specific things:

- [ ] Double encoding in PCF controls 
- [ ] Double encoding in Properties.json
- [x] Test cases. (see updates in https://github.com/microsoft/PowerApps-Language-Tooling/issues/52)

**Comment by MikeStall** [comment]
#161 - remove timestamp in sarif files.

**Comment by lesaltzm** [comment]
Sample Resources and Sample Data should not be written to the .msapp. The studio should be able to recreate them on load.
