### ISSUE TITLE
Fix organic failures

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Language-Tooling#212]
There are some crashes errors we're seeing from monitoring:

- [x] Error PA3001: Internal error. The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | <LineNumber> | <LinePosition>.
- [x] Error PA3005: Validation error: Group control Group6's state refers to non-existent child highLbl_2
- [x] Error PA3001: Internal error. Object reference not set to an instance of an object.
- [x] Error PA3001: Internal error. Object reference not set to an instance of an object.
- [x] Error PA3005: Validation error: Test Step Step22 references screen CheckBox,Toggle,Slider and Rating that is not present in the app

**Comment by suskumar-MSFT** [comment]
Have resolved all the telemetry issues, hence closing the bug.
