### ISSUE TITLE
Form element - enable lock property to remove 'custom field' in form fields

### ISSUE THREAD

**Issue by iBoonz** [microsoft/PowerApps-Language-Tooling#213]
When modifying Form fields locally, the field is changed from text, number, .. to custom field.  
Based on the functionality I see in the portal is that PowerApps is looking the locked property, could this property be added to the YAML?

Thanks

**Comment by lesaltzm** [comment]
This is an interesting question: Locking of controls is something we've considered "Editor state", since it isn't meaningful w.r.t the resulting app. Could you elaborate on why you'd want this to be part of the yaml? What scenarios would it enable for you?

**Comment by landonarogers** [comment]
Thank you for your suggestion! We've collected your feedback as a team and appreciate the time you've spent on this!
