### ISSUE TITLE
App not working after we unpack and pack it again

### ISSUE THREAD

**Issue by Nkumar1619** [microsoft/PowerApps-Language-Tooling#222]
The App is using a gallery control to populate data based on a collection. It works fine for the first time in the preview once we publish the app, it is not showing the data. Even though data is present in the gallery.

**Comment by MikeStall** [comment]
Collection data is temporary - so it may just be getting reset. 
Do you see the same behavior if you skip the pack/unpack and just import/export the msapp (without any pack/unpack involved)?

Are you getting any checksum mismatch errors on re-pack? Repacking should get the exact same msapp as before.

**Comment by Nkumar1619** [comment]
@MikeStall thanks for the response.

I do not see the same behavior when I export/import the msapp it works fine.

Whenever I pack/unpack the app it is not giving any checksum mismatch error. On uploading the repackaged app it works fine in preview. Once we publish the changes, it is not getting the data for that gallery. If we monitor the network call it is returning the data for that collection. 

Please let me know if you need any further details.

**Comment by MikeStall** [comment]
Is it possible to share the msapp with us? You can email it to jmstall at microsoft dot com.

**Comment by MikeStall** [comment]
@Nkumar1619  - can you share the msapp with us?

**Comment by MikeStall** [comment]
Resolving no repro  - if you do get a repro and can share the msapp, please reopen.
