### ISSUE TITLE
People Picker field out of order after import custom form

### ISSUE THREAD

**Issue by RoSchoe** [microsoft/PowerApps-Language-Tooling#225]
I migrate powerapps custom form from one tenant to an other.
After Importing and Upload / Publish the form the people picker field (drop down) is out of order.
I have a sharepoint list as backend and field of type person or group (person).

Items:
`Choices([@'SharePointList'].Personfield)` 

If i set a new field with the same information everything works fine.
Do i have to replace Azure AD ids or sth?

**Comment by lesaltzm** [comment]
To clarify, the data that shows up in that dropdown is out of order?

**Comment by RoSchoe** [comment]
It looks fine. But you can not Look for people anymore, it stays blank and seems to hung. The Text "find items" is missing too.
I have testet another Form - Same result. 
No warning, No Error. If you add same field again (fesh) it works.

**Comment by lesaltzm** [comment]
When you used this tool (PASopa), did you have any errors or warnings?

**Comment by RoSchoe** [comment]
No errors. - i did replace all Sharepoint List Ids by Script.
Then Pack everything and Import to powerapps gui

**Comment by RoSchoe** [comment]
I will check what happens if i do an Import without use of pasopa.

**Comment by RoSchoe** [comment]
I did an import without unpack and pack with pasopa - only replace list data in the "Microsoft.PowerApps\apps\ID\ID.json
 After the import to the list in the other tenant and remove replace all databases the people fields are fine.

That means the failure with the people field is caused by unpack, replace ids and pack the *.msapp

**Comment by RoSchoe** [comment]
I found a solution and the problem:
After import with PASopa the combobox field Allow searching is turn "off"
![image](https://user-images.githubusercontent.com/37191319/119327440-46d47b00-bc83-11eb-8efc-b704cda7fcd8.png)

If you set it to on - all is fine.
![image](https://user-images.githubusercontent.com/37191319/119327130-ee9d7900-bc82-11eb-9369-f3dfcd7b5acf.png)

**Comment by lesaltzm** [comment]
When you unpacked the app, was the `IsSearchable` property on that combobox  present?

**Comment by RoSchoe** [comment]
Same Problem in Combobox
Before Import Combobox
![image](https://user-images.githubusercontent.com/37191319/121249138-88307180-c8a4-11eb-9b66-e3a8e1060a70.png)


 -> After import Combobox
![image](https://user-images.githubusercontent.com/37191319/121248961-53241f00-c8a4-11eb-980e-7e905c9f375c.png)

That means it is a combobox search problem

**Comment by MikeStall** [comment]
If I just round-trip an app with a combo box, "Allow searching" roundtrips. 
I wonder if this is some IR reconstruction that somehow loses the IsSearchable property in a round-trip, but I can't repro it.

**Comment by jt000** [comment]
@RoSchoe, this may have been fixed as a part of another issue. Are you still able to reproduce this issue?
