### ISSUE TITLE
Unpack failing with PA3001: Internal error. Sequence contains no matching element

### ISSUE THREAD

**Issue by Chris-WP** [microsoft/PowerApps-Language-Tooling#252]
We have a large .msapp PowerApp that is failing to unpack using the PowerPlatform CLI v1.7.2 version of the tool.

Is that version of the CLI using the latest release from this repository (i.e. "0.3.1-preview")?

The error message we receieve is very generic:
```
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:b7429ee6-1ea7-44fd-b57f-96e9ca44ba83
```

Is there any functionality/command switch we can use to gain a more detailed verbose error message?

**Comment by Chris-WP** [comment]
After further investigation, using the compiled tool (PASopa) directly, I get an error message of:
```
PA3001: Internal error. Sequence contains no matching element
```

**Comment by MikeStall** [comment]
@Chris-WP  - can you send me a copy of your msapp and we can repo? Just email to jmstall at microsoft dot com.

**Comment by Chris-WP** [comment]
Thanks @MikeStall. I have just now emailed the .msapp file to your Microsoft email address.

**Comment by MikeStall** [comment]
Partial fix made. But there's still an issue with InvariantScript not round-tripping....

**Comment by suskumar-MSFT** [comment]
Made the remaining fix, it should work now.

**Comment by Chris-WP** [comment]
Thanks @MikeStall @suskumar-MSFT. I can confirm that my .msapp file now successfully unpacks using v0.3.4.
