### ISSUE TITLE
Transform Connections.json

### ISSUE THREAD

**Issue by crowcoder** [microsoft/PowerApps-Language-Tooling#259]
A major pain point for apps that use Sharepoint lists as data sources is that you have to edit them all when you move an app from one environment to another (e.g., dev to prod) . I noticed that PASopa.exe creates a Connectionsljson file that appears to be something I could use to change all the connections before importing the packed app. However, I'm not sure how to manage the object and connectionInstanceIds. When I play around with them all I get is:

`Error   PA3002: Format is not supported. Document consistency error. Connection id mismatch`

Understanding this may not be supported (yet?), what would the process be to transform sharepoint list ids before packing and importing into another environment?

**Comment by caburk** [comment]
The recommended approach for your scenario is to use environment variables. 

https://powerapps.microsoft.com/blog/announcing-data-source-environment-variables/
https://docs.microsoft.com/powerapps/maker/data-platform/environmentvariables#use-data-source-environment-variables-in-canvas-apps

**Comment by crowcoder** [comment]
Last I checked (and tried), sharepoint connections were not supported by environment variables. Has that changed?

**Comment by MikeStall** [comment]
@crowcoder  - one approach is to create 2 versions of your app (with sharepoint1 and sharepoint2) and then just unpack and diff them.
