### ISSUE TITLE
[Question] Understanding which version of the tool is included in which version of Power Platform CLI

### ISSUE THREAD

**Issue by Chris-WP** [microsoft/PowerApps-Language-Tooling#260]
Is there a document or command line switch that advises which release of the PowerApps-Language-Tooling is included in which version of the Power Platform CLI?

For example, I note that v1.7.4 of the Power Platform CLI has been released on Nuget, but I'm not sure whether that is using v0.3.3 or v0.3.2 of this tool.

Also, is a new version of the Power Platform CLI always released when a new version of the  PowerApps-Language-Tooling is released in this GitHub repository?

Gaining a better undertanding of the release mechanisms would be very helpful as this tool becomes an integral part of the CI/CD processes of community members.

**Comment by Chris-WP** [comment]
Thanks @MikeStall. Whilst in "preview", a table that shows CLI version to source version would be very helpful.

Especially as AA4AM (https://github.com/microsoft/coe-starter-kit/tree/main/ALMAcceleratorForAdvancedMakers) seems to be moving to use the Power Platform CLI.

**Comment by devkeydet** [comment]
@Chris-WP - The ALM Accelerator for Advanced Makers will only use Power Platform CLI as a temporary measure until the Power Platform Build Tools support canvas unpack/pack natively.  At the risk of speaking for the team that owns Power Platform Build Tools, our working plan is to assume native Power Platform Build Tools support for canvas unpack/pack won't likely come until https://www.nuget.org/packages/Microsoft.PowerPlatform.Formulas.Tools is GA.  To date, the public release of Power Platform Build Tools doesn't surface preview features.  Once Power Platform Build Tools supports canvas unpack natively, we will move to that asap and no longer use pac cli in our pipelines.  Until then, our reference pipelines will support the notion of specifying which version of pac cli you want to use in a pipeline run.  You can see this implemented in a feature branch here:

https://github.com/microsoft/coe-alm-accelerator-templates/blob/devkeydet-652/Pipelines/Templates/install-pac.yml

That way, you will be able to use the table of CLI version to source / nuget version that @MikeStall and team provide to make a decision about what version to use if running our reference pipelines.

This will be part of our next release.  We're waiting on the next version of pac cli to release, which incorporates bug fixes we ran into in testing while unpacking one of our CoE Starter Kit solutions.
https://github.com/microsoft/PowerApps-Language-Tooling/issues/248

When we run into breaking changes in the format, we've been running a new export of all our canvas apps to stay in sync with the latest format.

**Comment by MikeStall** [comment]
@Chris-WP  - I've added that table to the readme, https://github.com/microsoft/PowerApps-Language-Tooling/blob/master/README.md#versioning

**Comment by Chris-WP** [comment]
Thanks @MikeStall. Much appreciated.
