### ISSUE TITLE
Doesn't work on mac os

### ISSUE THREAD

**Issue by ArsyMus** [microsoft/PowerApps-Language-Tooling#261]
Can't build on mac os. Returns an error.

**Comment by MikeStall** [comment]
What error are you seeing?

Our CI does build on mac and linux on each commit. For example:
https://github.com/microsoft/PowerApps-Language-Tooling/pull/256/checks?check_run_id=2947292597

**Comment by landonarogers** [comment]
Hey @ArsyMus ; Are you still seeing this issue? Thanks!
