### ISSUE TITLE
Getting error "Round trip Validation on unpack failed"

### ISSUE THREAD

**Issue by mehakvij** [microsoft/PowerApps-Language-Tooling#273]
Getting an error when unpacking a canvas solution:

![image](https://user-images.githubusercontent.com/73190679/125636758-28da3850-3c07-4a1d-b069-b5ca81bb87d5.png)

![image](https://user-images.githubusercontent.com/73190679/125636817-0d559a27-7d0b-4405-b956-f8b4c1cb9eac.png)

How can this be fixed?

**Comment by suskumar-MSFT** [comment]
@mehakvij bunch of roundtrip errors were recently fixed, could you try with the latest code and see if you still hit this issue? If you do, could you share the msapp file with us so that we can take a look?

**Comment by suskumar-MSFT** [comment]
the bug is fixed, the fix would be available in the next CLI release.
