### ISSUE TITLE
When Pack a solution an Exception with a non recoverable error.

### ISSUE THREAD

**Issue by ejcasas** [microsoft/PowerApps-Language-Tooling#304]
C:\Users\xxxxxxxxxx\Documents\GitHub\SolutionPath> pac canvas pack --sources c:\users\51190494\Documents\GitHub\SolutionPath --msapp c:\users\xxxxxxxxxx\Documents\GitHub\SolutionPath
Pack from c:\users\xxxxxxxxxx\Documents\GitHub\Perks-->c:\users\xxxxxxxxx\Documents\GitHub\SolutionPath
  source format version: 0.24

"Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded 
to the development team, if telemetry has been enabled. Exception Id:490e1246-2291-430b-b51d-776dcceed5c9"

Thanks a lot,
Henry

**Comment by MikeStall** [comment]
Do you have access to the directories you're using?  Based on the id, this is an System.UnauthorizedAccessException  exception from: 

```
{"assembly":"System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.IO.Compression.ZipFile.Open","level":3,"line":0} 
{"assembly":"Microsoft.PowerPlatform.Formulas.Tools, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.PowerPlatform.Formulas.Tools.MsAppSerializer.SaveAsMsApp","level":4,"line":0}
{"assembly":"Microsoft.PowerPlatform.Formulas.Tools, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.Wrapper","level":5,"line":0}
{"assembly":"Microsoft.PowerPlatform.Formulas.Tools, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.SaveToMsApp","level":6,"line":0}
{"assembly":"bolt.module.canvas, Version=1.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"bolt.module.canvas.PackCommand.ExecuteAsync","level":7,"line":0}


```

That said, we should still display the error to the user to aide in diagnosing.

**Comment by ejcasas** [comment]
That solved the problem. Thank you very much!!!!
