### ISSUE TITLE
Unconsistent .fx.yaml

### ISSUE THREAD

**Issue by nmedda** [microsoft/PowerApps-Language-Tooling#305]
Hi there,

First of all, thanks for what you're doing. You're making my life so much easier 🙏 .

Regarding my issue now.
I'm in the process of implementing ALM. One of the objective is to have code reviews when a feature is complete.
My idea was that we could export the app, unpack it, commit the changes and then make a pull request.
My issue is that my screen  `fx.yaml` changes a bit too much and generate a lot of noise, which is not pleasant for a good review.

My main problem is that the order of the components can change in the generated file for no apparent reason (no component added, moved or removed in the editor, just formulas).
Git doesn't understand this very well and can give some funky diffs.

I don't know if there's an issue that I should have commented or followed instead of creating my own. Let me know, and I'll do my best.

**Comment by MikeStall** [comment]
We'd like the .fx.yaml to be stable and avoid "noisy diffs". The tool tries to stabilize things on unpack. 
Can you send some examples of the diffs you're seeing either to this comment thread (public) or privately to 'jmstall at microsoft dot com'?

**Comment by nmedda** [comment]
Hi,
Here is my latest diff.

(https://github.com/nmedda/pac/commit/a28aa3e466be0269e565d353c3ec3d23d244f35a)

I just added the `.yaml` to showcase just my pb. If you need something else, let me know

**Comment by MikeStall** [comment]
@nmedda  - I see the commit, thanks. What change did you make here?  Ie, how small _should_  the diff have been?
It looks like this is related to cards.

**Comment by nmedda** [comment]
Hi, sorry for the delay, vacation time :)

@MikeStall, I created the expected diff on the master branch : https://github.com/nmedda/pac/commit/4e0173c5518ee0eba7616eaf45cf9653d4951d72

Compared to nmedda/pac@a28aa3e

My example is maybe not the best one, I thought I picked a commit with only a few changes, but it appears I renamed a bunch of object due to typo and naming convention in my team.

Anyway, I didn't change the order of object in studio, so I would have expected the generated code to look like the "expected diff"

Let me know if you need anything else.

**Comment by epujadas-kaefer** [comment]
Hello,

First, thank you very much for the tool development, its really great and it saved me lots of time!

I can't figure out how the tool chooses to name certain variables, whenever I unpack an .msapp, the variable names seem to alternate between their real name and a pseudonym? Don't know how to call it...

Example: Full_x0020_Name to 'Full Name', and vice versa.

This creates lots of noisy diffs when viewed in an IDE, and makes it difficult to see the real changes.

This is a real example of the same APP unpacked, with no changes in-between:
![image](https://user-images.githubusercontent.com/82584686/154259036-3ce035e3-af6c-4874-a406-88d836f18dda.png)

In my case the data source is a Sharepoint list.

I wanted to create another issue but this one is very similar to what i'm experiencing, hope this is the right call.

**Comment by MikeStall** [comment]
@epujadas-kaefer  - the tool _shouldn't_ be interfering with formula content.  0x20 is ascii for space, so it looks like Full_x0020_Name is an escaped version of 'Full Name'.  Are the left and the right just taking the same msapp and unpacking it twice? if so, can you file a new issue for that? It's different than the noisy issue first reported here.

**Comment by MikeStall** [comment]
I think for the original issue @nmedda is reporting, we need to ensure that the controls in the fx.yaml are being listed in a canonical order (ie, alphabetical). 

Example from his diff: 
https://raw.githubusercontent.com/nmedda/pac/a28aa3e466be0269e565d353c3ec3d23d244f35a/Formulaire.fx.yaml

**Comment by tomjschneider** [comment]
This issue is being reevalauted as the fix needed to be rolled back.

**Comment by arpavan** [comment]
This issue is being further investigated internally and based on our findings we believe it may not be an issue with PALT at this point. Closing this issue.
