### ISSUE TITLE
Error   PA3005: Validation error: Connection does not have a corresponding data source.

### ISSUE THREAD

**Issue by famastefano** [microsoft/PowerApps-Language-Tooling#308]
Hello,
just downloaded the extension for VS and tried to unpack an app but this error shows up:
`Error PA3005: Validation error: Connection 'Docs_1' does not have a corresponding data source.`

The fact is that I can't see **Docs_1** anywhere in the Data Sources, maybe it was removed, I don't know.

```
Microsoft PowerPlatform CLI
Versione: 1.9.4+gbda9f20
```

**Comment by Bregor-Mar-Rian** [comment]
Same issue here. It fails with the same type of error.
The app had a data connection that was removed at some point in a standard way.

For some of our other apps (where we also deleted certain old data connections), same [unpack](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/cli/reference/canvas-command#:~:text=msapp%20HelloWorld.msapp-,unpack,-Unpacks%20the%20.msapp) seems to work fine.

The only place we can see a reference to the old connection in is the exported package (zip) version:
Microsoft.PowerApps → apps → [app_unique_number] → [app_unique_number].json → appDefinitionTemplate → properties → connectionReferences → dataSources

Currently, this is a show-stopper for our app that needs source control the most.
How can we fix this error ?

**Comment by MikeStall** [comment]
Can you email your msapp to jmstall at microsoft dot com

**Comment by landonarogers** [comment]
The latest version of the PAC CLI (1.13.4) has been released which includes support for this issue. If you are still experiencing roundtripping errors on the latest version of the CLI, please open a new Issue in the repo.
