### ISSUE TITLE
Unable to Unpack App

### ISSUE THREAD

**Issue by DaveStabilify** [microsoft/PowerApps-Language-Tooling#317]
I am receiving the following error for a few of our larger Canvas Apps:

PA3001: Internal error. An item with the same key has already been added. Key: Microsoft.PowerPlatform.Formulas.Tools.Utility.FilePath

Any ideas?

**Comment by MikeStall** [comment]
Can you email your msapp to us at jmstall at microsoft dot com?

Are you running PASopa.exe from repository? Or are you using via the Power Apps CLI?

**Comment by NimbiMac** [comment]
Any update on this issue? I am getting the same when trying to unpack an msapp. Running PASopa.exe and get this message: 
" PA3001: Internal error. An item with the same key has already been added. Key: groupContainer"

Also tried with Power Apps CLI and still failed with this message: 
"Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:3cfd9218-2e70-4cf4-be14-e213bb0f8e5a"

**Comment by Ajeeboy** [comment]
Any update on this issue , I am also gettiing this error message ; Error   PA3001: Internal error. An item with the same key has already been added. Key: groupContainer 

Using the PASOPA librraies to unpack my msapp file on my local machine

**Comment by TheFoolFred1** [comment]
Add me to the list of people experiencing Error PA3001: Internal error. An item with the same key has already been added. Key: groupContainer when trying to unpack.

I, too, am using PASopa.exe on my local machine.

I have been able to successfully unpack other programs without issue.

I recently had one program that kicked up an error (different from the above error) and painstakingly copied the entire app control-by-control.  I stopped at intervals to unpack the *.msapp hoping to find the cause.  I did this 20 times before I finished and never had an error.  When I finished, I had recreated the one that was not unpacking but it successfully would unpack.  I am about to go through the same process with the app I am currently unable to unpack if I have to.

Is there anything I can check for that might cause the SASopa.exe to fail?

I would gladly email you the msapp for the currently problem if it would help.

**Comment by MikeStall** [comment]
@TheFoolFred1  - can you email me your msapp at jmstall at microsoft dot com

**Comment by IC-Jonathan-Roussel** [comment]
We're getting a pretty similar error to TheFoolFred1 above with PowerApps v3.22015.22.
When unpacking a few of our PowerApps, we received a few of the following errors which caused unpacking to fail.
`PA3001: Internal error. An item with the same key has already been added. Key: groupContainer`

We are running PASopa.exe from repository, not using the Power Apps CLI.

I've been instructed not to share the msapp file if there's anything we can check for ourselves first.
Is there anything recommended for us to check for?

**Comment by NavneetThekkumpat** [comment]
@IC-Jonathan-Roussel : can you mail me your msapp as a repo, at nthekkumpat at microsoft dot com?

**Comment by NavneetThekkumpat** [comment]
The latest version of the PAC CLI (1.13.4) has been released which includes a fix for the error reported here. If you are still experiencing roundtripping errors on the latest version of the CLI, please open a new Issue in the repo.
