### ISSUE TITLE
Build Fails with latest .net 3.1.414

### ISSUE THREAD

**Issue by melzoghbi** [microsoft/PowerApps-Language-Tooling#321]
Hi,
When i try to build the tooling package. I am getting the following error:

![image](https://user-images.githubusercontent.com/11993393/141598324-b59b6da4-2b3f-42e0-95b6-d0951255fade.png)

**Comment by PratikSoni2889** [comment]
@melzoghbi : any luck with this issue? I am also facing the same.

**Comment by landonarogers** [comment]
Thank you for reaching out! As of now, I would try using version 3.1.418.
