### ISSUE TITLE
Unable to run build.cmd on Windows ARM

### ISSUE THREAD

**Issue by Stevak** [microsoft/PowerApps-Language-Tooling#323]
Hi, 
I'm not sure whether I have missed something or they should do anything special on Windows ARM, but I'm trying to run build.cmd but don't see the new folders appear, which brings me to the conclusion that it wasn't installed for some reason.
is there any solution for this?

**Comment by jt000** [comment]
Hi @Stevak, we unfortunately don't currently support ARM at this time for this library
