### ISSUE TITLE
PA3011: Roundtrip validation on unpack failed (latest Power Apps update)

### ISSUE THREAD

**Issue by JoshNewham1** [microsoft/PowerApps-Language-Tooling#324]
Hi there,

With the latest version of Power Apps Studio (3.21113.12), it seems 'pac unpack' has stopped working for me, but it seems to be only with apps using custom "Dataverse for Teams" controls (e.g. the modern text box). I've attached a test solution where this problem occurs - it's inconvenient at the moment but I can revert to the previous version of Power Apps and it will continue working.

![image](https://user-images.githubusercontent.com/25721451/144916314-de6d521a-306c-49e7-8c71-53850a8495ee.png)

Cheers,
Josh

[TestSolution_1_0_0_1_managed.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/7663345/TestSolution_1_0_0_1_managed.zip)

**Comment by tomjschneider** [comment]
Validated this was resolved with [PR 351](https://github.com/microsoft/PowerApps-Language-Tooling/pull/351). This will be available in the next release of the PAC CLI.
