### ISSUE TITLE
Roundtrip validation on unpack failed. Mysterious AppTests folder causing issues

### ISSUE THREAD

**Issue by MattTrinder1** [microsoft/PowerApps-Language-Tooling#325]
I'm getting the above error trying to unpack the attached (zipped) app.

[cp_suddendeathazurecontinuous_49558_DocumentUri.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/7705237/cp_suddendeathazurecontinuous_49558_DocumentUri.zip)

**Comment by MattTrinder1** [comment]
This error only occurs if there is a single empty test case present - once the case has had a single step added the error no long happens.

**Comment by tomjschneider** [comment]
This issue has been merged into the Power Platform CLI and will be available in the next release.
