### ISSUE TITLE
PA3011: Roundtrip validation on unpack failed.

### ISSUE THREAD

**Issue by guenthi** [microsoft/PowerApps-Language-Tooling#328]
Receiving "PA3011 Roundtrip validation on unpack failed" error when unpacking our canvas app with pac cli 1.10.4+gf23be2f

Despite of the error-message, the command unpacks the canvas app. The produced output-source can be packed with PA-2001 check-sum warning.

Full output of pac canvas unpack:
UnPack from d:\Temp\pac\CanvasApps\name-of-app.msapp-->D:\temp\pac\tmp
  source format version: 0.24
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Microsoft PowerPlatform CLI
Version: 1.10.4+gf23be2f

Error: There were errors.

Usage: pac canvas unpack [--sources] --msapp

  --sources                   Directory to sources to be unpacked
  --msapp                     Path to .msapp file

**Comment by jenschristianschroder** [comment]
Do you have any Dataverse for Teams controls in you canvas app? That will fail the roundtrip validation and result in the experience you describe.

**Comment by guenthi** [comment]
within the app we have created 3 very simple custom components - beside these we are just using the out-of-the box objects/controls. the unpacking broke around 3 weeks ago - in this timeframe we did not make an changes to the custom components

**Comment by MikeStall** [comment]
@guenthi  - can you mail me your msapp as a repo, at jmstall at microsoft dot com?

**Comment by wjhepworth-tt** [comment]
@MikeStall - We are experiencing the same situation.  No teams or CDS involved.  This app does use components and containers.  It's been generally working.  If this helps, we have the following resources:

- Separate component library
- Custom connectors pointing to APIs
- SQL Server connectors

**Comment by landonarogers** [comment]
This specific issue is fixed now as of this pull request: https://github.com/microsoft/PowerApps-Language-Tooling/pull/351 . The fix will be available in the next version of the PAC CLI.

Note: 'Roundtrip validation on unpack' may appear again, but it should not for this issue (as the issue should be fixed). This is more of a broad message that can occur from a number of different issues.
