### ISSUE TITLE
support inline excel

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Language-Tooling#331]
Apps with inline excel don't unpack.
 
Attaching an example. (Git won't let you attach an .msapp file, so rename .msapp.zip --> .msapp)
[InlineExcel.msapp.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/7849289/InlineExcel.msapp.zip)

**Comment by NavneetThekkumpat** [comment]
I couldn't reproduce the same, not sure if this happens still.  (tried unpacking using pac and pasopa)

**Comment by MikeStall** [comment]
This appears to be working.   The excel sheet is being passed inline in the data of a data source. 

        {
            "Name": "SimpleTable",
            "Schema": "*[Name:s, Score:n, Score2:n]",
            "IsSampleData": false,
            "IsWritable": false,
            "Type": "StaticDataSourceInfo",
            "OriginalSchema": "*[Name:s, Score:n, Score2:n]",
            "Data": "[{\"Name\":\"Fred\",\"Score\":100,\"Score2\":12},{\"Name\":\"Ted\",\"Score\":200,\"Score2\":32},{\"Name\":\"Ed\",\"Score\":300,\"Score2\":45},{\"Name\":\"Ned\",\"Score\":400,\"Score2\":51}]",
            "Token": "dummyToken",
            "OriginalName": "SimpleTable",
            "OrderedColumnNames": [
                "Name",
                "Score",
                "Score2"
            ]
        }
