### ISSUE TITLE
 pack and unpack power platform solution.

### ISSUE THREAD

**Issue by Naim62467** [microsoft/PowerApps-Language-Tooling#333]
Hi All,

I am facing solution unpack issue when I am trying to push code in ALM git.
 Roundtrip validation on unpack failed. This is always a bug, please file an issue. 
 
 Error is below:
 
 Generating script.

========================== Starting Command Output ===========================

"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\00f18937-0d9c-490f-a29c-3a4c6cc06b4d.ps1'"

UnPack from D:\a\1\s\MnS_Pest_Walk_App\MSPestWalkApp\SolutionPackage\CanvasApps\msretail_pestwalkcheck_8ad06_DocumentUri.msapp-->D:\a\1\s\MnS_Pest_Walk_App\MSPestWalkApp\SolutionPackage\CanvasApps\msretail_pestwalkcheck_8ad06_DocumentUri_msapp_src

source format version: 0.24

Error PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling

Error PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling

Microsoft PowerPlatform CLI

Version: 1.10.4+gf23be2f

Error: There were errors.

Usage: pac canvas unpack [--sources] --msapp

--sources Directory to sources to be unpacked

--msapp Path to .msapp file

##[error]PowerShell exited with code '1'.

Finishing: unpack msapp files

<img width="549" alt="unpach solution issue" src="https://user-images.githubusercontent.com/86398538/149449780-9f8b0647-d478-4352-a66d-26f02fb2d667.png">

**Comment by MikeStall** [comment]
Can you email your msapp to jmstall at microsoft dot com?

**Comment by Naim62467** [comment]
> Can you email your msapp to jmstall at microsoft dot com?

I have email you. thanks

**Comment by Naim62467** [comment]
> Can you email your msapp to jmstall at microsoft dot com?

Hi Mike, If I am trying to work on other app still I am facing same issue for my other app. Kindly suggest.

**Comment by tomjschneider** [comment]
Hi @Naim62467. I'm currently looking into this issue and what may be causing it. 

I believe it may have something to do with the screen in your app `GetsupportScreen` having the same name as your component `GetSupportscreen`. 

If you'd like to work around this while I investigate further, you can use the `PASopa.exe` in this repo directly. Directions for doing this can be found [in the repo README](https://github.com/microsoft/PowerApps-Language-Tooling#test-app-usage). If you do so, could you try renaming the screen to something like `GetsupportScreen_2`, running the `PASopa.exe` directly, and letting me know if that fixes the problem?

I will update this when I have discovered more information on this issue.

**Comment by mpil** [comment]
Hey @tomjschneider, I am experiencing the same problem. I have cloned this repo and ran PASopa.exe locally, this is what I received:

![2022-02-08_14h19_52](https://user-images.githubusercontent.com/11491812/152995508-2ed2b6b9-c1bc-4125-8d41-71ffaf38e97e.png)

Any thoughts?

**Comment by tomjschneider** [comment]
Hey @mpil, can you email your msapp to tschneider at microsoft dot com and I will take a closer look?

**Comment by mpil** [comment]
> Hey @mpil, can you email your msapp to tschneider at microsoft dot com and I will take a closer look?

@tomjschneider Email sent.

**Comment by tomjschneider** [comment]
This issue has been merged into the Power Platform CLI and will be available in the next release.
