### ISSUE TITLE
Error unpacking Custom Pages msapp files 

### ISSUE THREAD

**Issue by devkeydet** [microsoft/PowerApps-Language-Tooling#338]
I am using custom pages:
https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-page-to-model-app
When I try to unpack msapp files that are pages, I get the following errors.  Attached is the solution that is causing the errors.
[CutstomPageTest.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/7977772/CutstomPageTest.zip)

  _source format version: 0.24
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Microsoft PowerPlatform CLI
Version: 1.11.3+g2dacf1a

Error: There were errors.

Usage: pac canvas unpack [--sources] --msapp

  --sources                   Directory to sources to be unpacked
  --msapp                     Path to .msapp file_

**Comment by NavneetThekkumpat** [comment]
Tested unpacking the .msapps mentioned with the latest PAC CLI (Version: 1.14.2+g7205df7). 
Unpacks successfully and seems like this issue is resolved and hence closing this issue.
Please feel free to open a new issue if this persists in future.
