### ISSUE TITLE
unpack msapp files fails with PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/PowerApps-Language-Tooling#347]
We are getting "PA3011 Roundtrip validation on unpack failed" error when unpacking canvas app with PAC CLI 1.11. The error fails our pipelines and prevents us to source control the solution.

Full output of pac canvas unpack:

```
UnPack from D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_makerassessment_505f3_DocumentUri.msapp-->D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_makerassessment_505f3_DocumentUri_msapp_src
  source format version: 0.24
UnPack from D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_makerassessmentadminapp_1f3f4_DocumentUri.msapp-->D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_makerassessmentadminapp_1f3f4_DocumentUri_msapp_src
  source format version: 0.24
UnPack from D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_powerplatformtrainingregistration_4c1ca_DocumentUri.msapp-->D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_powerplatformtrainingregistration_4c1ca_DocumentUri_msapp_src
  source format version: 0.24
UnPack from D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_templatecatalog_64572_DocumentUri.msapp-->D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_templatecatalog_64572_DocumentUri_msapp_src
  source format version: 0.24
UnPack from D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_traininginadaymanagement_3a72b_DocumentUri.msapp-->D:\a\1\s\coe-starter-kit\CenterofExcellenceNurtureComponents\SolutionPackage\CanvasApps\admin_traininginadaymanagement_3a72b_DocumentUri_msapp_src
  source format version: 0.24
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Microsoft PowerPlatform CLI
Version: 1.11.8+gb7437cd

Error: There were errors.

Usage: pac canvas unpack [--sources] --msapp

  --sources                   Directory to sources to be unpacked
  --msapp                     Path to .msapp file
```

I'm attaching the managed version of the solution
[CenterofExcellenceNurtureComponents_2_6_2_managed.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/8090648/CenterofExcellenceNurtureComponents_2_6_2_managed.zip)

Let me know if you need any further info!

**Comment by raphaelcharreyron-bib** [comment]
Same issue on our side...
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\7079b4a0-8bc6-4e16-b14d-e7564a43fb54.ps1'"
UnPack from D:\a\1\s\MQ - DevOps Maturity\DevOpsMaturity\SolutionPackage\CanvasApps\new_devopsmaturity_b1253_DocumentUri.msapp-->D:\a\1\s\MQ - DevOps Maturity\DevOpsMaturity\SolutionPackage\CanvasApps\new_devopsmaturity_b1253_DocumentUri_msapp_src
  source format version: 0.24
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
Microsoft PowerPlatform CLI
Version: 1.12.2+gf0f06de

Error: There were errors.

Usage: pac canvas unpack [--sources] --msapp

  --sources                   Directory to sources to be unpacked
  --msapp                     Path to .msapp file

##[error]PowerShell exited with code '1'.

**Comment by winterscar** [comment]
Same on our side, happy to provide an msapp if needed.

**Comment by winterscar** [comment]
Hotfix (although this is kinda sketchy):
Add this in export-Solution.yml 
```diff
# Use temp exe from PowerShell to unpack source files into a folder
 - pwsh: |
   Get-ChildItem -Path "$(Build.SourcesDirectory)\${{parameters.repo}}\${{parameters.solutionName}}" -Recurse -Filter *.msapp | 
   ForEach-Object {
      $unpackedPath = $_.FullName.Replace(".msapp", "_msapp_src")
      $env:PATH = $env:PATH + ";" + "$(pacPath)"
      pac canvas unpack --msapp $_.FullName --sources $unpackedPath
      del $_.FullName
   }
  displayName: 'unpack msapp files'
  enabled: true
+ continueOnError: true
```

**Comment by NPrice99** [comment]
Hi 
I also got this issue when unpacking Admin - Control Centre from the Microsoft CoE
Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling
1 errors, 4 warnings.

Regards

Nigel

**Comment by tomjschneider** [comment]
Marking as in next release and will close this Issue when the change is added to the Power Platform CLI.

**Comment by richardhardinguk** [comment]
We're struggling with this too - I see there's a fix in the codebase now and this is marked as in next release, but when will the next release be? Thanks!

**Comment by tomjschneider** [comment]
This fix has been complete in this repo and integrated into the Power Platform CLI. We're just waiting for the next release of the Power Platform CLI and this issue should be resolved. I don't have a specific date for that release, but will comment on this when the release is complete.
