### ISSUE TITLE
When I export its exporting as zip but command says use .msapp

### ISSUE THREAD

**Issue by swiftinitdotcom** [microsoft/PowerApps-Language-Tooling#349]
When I export its exporting as zip but command says use
.msapp
How to use it as msapp

**Comment by epujadas-kaefer** [comment]
Inside the app editor, go to "File", then "Save as", and then "my computer" or something along those lines.

![image](https://user-images.githubusercontent.com/82584686/154968839-371d96d2-98a9-4422-a9b1-87e2a2b82388.png)

Or alternatively you can find the .msapp inside that .zip.

Hope I could help!

**Comment by jt000** [comment]
@swiftinitdotcom - I'm guessing the ZIP that you are seeing is the solution export, which as @epujadas-kaefer mentioned will contain your .msapp. Alternatively, saving to your computer is a way to directly download the MSApp. 

Hope this helps. If not, please feel free to reopen.
