### ISSUE TITLE
Roundtrip Validation on Unpack Failed

### ISSUE THREAD

**Issue by joseph-parker-95** [microsoft/PowerApps-Language-Tooling#357]
![image](https://user-images.githubusercontent.com/101288394/157735186-da7e42a0-c37c-41ac-99c6-3414ca96c6ab.png)

Another bug  -- this has been repeating constantly for me!

**Comment by NavneetThekkumpat** [comment]
@joseph-parker-95 can you mail me your msapp as a repo, at nthekkumpat at microsoft dot com?
