### ISSUE TITLE
Roundtrip validation on unpack failed.

### ISSUE THREAD

**Issue by jansonjc** [microsoft/PowerApps-Language-Tooling#366]
**Describe the bug**
The following error was output twice while trying to unpack a CanvasApps msapp file.

`Error   PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling`

Reproduced using PAC CLI Version: 1.13.4+g79187cf

**To Reproduce**

1. Unpacking 
2. `pac canvas unpack --sources folder --msapp app.msapp`

The file did unpack but resulted in the above error.

**Screenshots**
![canvas-unpack-error](https://user-images.githubusercontent.com/20315731/159721813-4c37fd9e-5cfb-4048-8d89-af19bb76063e.png)

**Additional context**

The .msapp is part of a Dataverse solution and was exported using "pac solution export" and "pac solution unpack" commands. The .msapp inside the CanvasApp folder was unpacked using "pac canvas unpack" command

**Comment by NavneetThekkumpat** [comment]
@jansonjc can you mail me your msapp as a repo, at nthekkumpat at microsoft dot com?

**Comment by jjaramillo** [comment]
I can confirm this also happens to my team.
Our app uses both pcf code components and components stored on a custom component library
Switching back to version 1.12.2 allows us to extract the canvas app

**Comment by landonarogers** [comment]
@jansonjc If you're still experiencing roundtrip errors:

We've updated the error message to be much more descriptive. If you run `pac install latest`, and then try again, you will get updated error messages. Please post the new ones in a new GitHub issue. We appreciate your time to file these bugs and we also appreciate your patience!

**Comment by jjaramillo** [comment]
> Hey, @jjaramillo! The issue that you've mentioned seems to pertain more to #372. We're closing this issue, but please feel free to track your issue there as that ticket will still be open. Thank you for your time and patience!

Apparently the issue was being triggered because there was an empty test suite on the app's tests. Once we fixed that everything went fine
