### ISSUE TITLE
Roundtrip validation fails for PCF localization changes of adding a new property DisplayNameKey

### ISSUE THREAD

**Issue by yiwl0612** [microsoft/PowerApps-Language-Tooling#369]
- [x] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**

The PA ALM check fails for the msapp with the changes of adding a new property "DisplayNameKey" to the PowerAppsControl and there is a diff in the checksum.
![image](https://user-images.githubusercontent.com/62676091/159822799-32f8acd8-773d-48e6-8114-a87cc80a75e2.png)

[LocalFinnishBasedApp (1) - Copy.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/8337651/LocalFinnishBasedApp.1.-.Copy.zip)

**To Reproduce**

Download the attached .msapp and run `PaSopa -unpack` against it.

**Comment by jack-work** [comment]
A property was added to the schema for PcfJson in a recent change to the internal PowerApps-Client repo.  Because the property was not included in the PowerApps-Language-Tooling repo, the value is discarded.
