### ISSUE TITLE
Components hash mismatch with AllowAccessToGlobals property value changed

### ISSUE THREAD

**Issue by NavneetThekkumpat** [microsoft/PowerApps-Language-Tooling#380]
Components hash mismatch with AllowAccessToGlobals property value changed while unpacking the .msapp

**Describe the bug**
Reproducible using pac and pasopa unpack

**To Reproduce**

1. Unpacking

**Screenshots**

If applicable, add screenshots of error messages to help explain your problem.
![image](https://user-images.githubusercontent.com/98551644/162782747-2ab88ccb-6586-4d0f-b856-da821d43ff79.png)

**Additional context**

**Comment by arpavan** [comment]
This is a known issue with apps generated in a previous version of Power Apps Studio where the property in the msapp associated with the Access App Scope property for a custom component can get out of sync with other same property in other locations within the msapp file structure. We've documented the resolution steps via a workaround for this and other similar known issues in our [Known Issues document](/docs/KnownIssues.md)
