### ISSUE TITLE
Setup backcompat tests 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Language-Tooling#41]
Setup some backcompat tests to verify that the sources are stable.

**Comment by landonarogers** [comment]
@MikeStall Is this issue still in progress?

**Comment by jt000** [comment]
Note that Backward Compatibility is not garunteed at this time while in Preview. As needed, tests on Yaml Pack\Unpack will be added on a case-by-case basis for supported scenarios.
