### ISSUE TITLE
Error on unpack with unused Dataverse data source

### ISSUE THREAD

**Issue by LukasSchauffele** [microsoft/PowerApps-Language-Tooling#442]
- [x] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

[Manage Your Groups.msapp.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/9712223/Manage.Your.Groups.msapp.zip)

**Describe the bug**

Please mention if it is reproduced using PAC CLI or PASopa. *(Please mention the version number, if possible)*

**I was able to identify the issue as I was writing the bug report.**

### Cause & Workaround

I had an unused Dataverse Data Source in the application. Once I removed the Data Source, I was able to successfully unpack the solution.

See working msapp file (with dataverse data source removed):

[Manage Your Groups - Unused Data Source Removed.msapp.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/9712441/Manage.Your.Groups.-.Unused.Data.Source.Removed.msapp.zip)

### Original Bug Report

Getting error when unpacking [attached msapp file](https://github.com/microsoft/PowerApps-Language-Tooling/files/9712223/Manage.Your.Groups.msapp.zip). 

Encountered bug when running Power Platform Build Tools as part of ALM Accelerator for Power Platform

Task         : Power Platform Unpack Solution
Version      : 2.0.7

Then exported msapp file manually and was able to reproduce using pac

Microsoft PowerPlatform CLI
Version: 1.18.4+g1a00e63

```
Downloads pac canvas unpack --msapp "Manage Your Groups.msapp" --sources src 
Warning: canvas unpack is in preview, and functionality is not guaranteed. Use extreme caution if using in a production environment. For more information see https://aka.ms/paccanvas
Unpack from /Users/lukask/Downloads/Manage Your Groups.msapp --> /Users/lukask/Downloads/src
  source format version: 0.24
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Microsoft PowerPlatform CLI
Version: 1.18.4+g1a00e63

Error: Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[0].Capabilities.PCFExternalServiceUsageAllowed
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[0].ComponentName
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[0].Identifier
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[0].IdentifierType
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[1].Capabilities.PCFExternalServiceUsageAllowed
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[1].ComponentName
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[1].Identifier
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[1].IdentifierType
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[2].Capabilities.PCFExternalServiceUsageAllowed
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[2].ComponentName
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[2].Identifier
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[2].IdentifierType
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[3].Capabilities.PCFExternalServiceUsageAllowed
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[3].ComponentName
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[3].Identifier
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[3].IdentifierType
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[4].Capabilities.PCFExternalServiceUsageAllowed
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[4].ComponentName
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[4].Identifier
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[4].IdentifierType
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[5].Capabilities.PCFExternalServiceUsageAllowed
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[5].ComponentName
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[5].Identifier
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.components[5].IdentifierType
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.instanceUrl
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.state
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.webApiVersion
Error   PA3011: Roundtrip validation on unpack failed. 
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling
```

**To Reproduce**

1. Download attached msapp file
2. Run `pac canvas unpack --msapp "Manage Your Groups.msapp" --sources src`

**Screenshots**

If applicable, add screenshots of error messages to help explain your problem.

**Additional context**

Add any helpful context on the .msapp like created from teams, contains custom pcf components, etc.

Application contains code and canvas components from [Creator Kit](https://github.com/microsoft/powercat-creator-kit)

Code components:

- Fluent Command Bar (1.0.8)
- Fluent Details List (1.0.8)
- Fluent Elevation (1.0.8)

Library components:

- Panel
- SearchBox

Connectors:

- Office365Users
- Office365Groups
- Dataverse (Accounts) -- This was the culprit.

**Comment by NavneetThekkumpat** [comment]
Marking this as 'in next release' and will be completed once changes are in next release of the Power Platform CLI.

**Comment by NavneetThekkumpat** [comment]
Closing this issue, since the fix is out in the latest releases.
