### ISSUE TITLE
Folder with spaces causes Build.cmd to fail

### ISSUE THREAD

**Issue by diegopozzi1** [microsoft/PowerApps-Language-Tooling#443]
I'm trying to "install" the tool but the build.cmd gives me always the same error:

![build cmd](https://user-images.githubusercontent.com/93269508/194581978-f4f68054-86d7-4102-ad52-3d7d852cfe3d.png)

**Comment by jt000** [comment]
Hi @diegopozzi1, thanks for reporting. Can you attach the full build logs?

**Comment by diegopozzi1** [comment]
Hi @jt000  I'm not able to find logs under the execution path

the whole powershell session:

PS C:\Users\diego.pozzi\OneDrive - MyCompanyName\Documenti\GitHub\PowerApps-Language-Tooling> .\build.cmd

Unable to find root directory using git, assuming this script is being run from root = C:\Users\diego.pozzi\OneDrive - MyCompanyName\Documenti\GitHub\PowerApps-Language-Tooling
rebuild: Starting... (rebuild)
rebuild: clean: Starting...
targets: dotnet clean C:\Users\diego.pozzi\OneDrive - MyCompanyName\Documenti\GitHub\PowerApps-Language-Tooling\src/PASopa.sln --configuration Debug /clp:verbosity=minimal /flp:Verbosity=normal;LogFile=C:\Users\diego.pozzi\OneDrive - MyCompanyName\Documenti\GitHub\PowerApps-Language-Tooling\obj\logs/clean-Debug.log /flp3:PerformanceSummary;Verbosity=diag;LogFile=C:\Users\diego.pozzi\OneDrive - MyCompanyName\Documenti\GitHub\PowerApps-Language-Tooling\obj\logs/clean-Debug.diagnostics.log  /nologo
MSBUILD : error MSB1008: Only one project can be specified.
Switch: Beta

For switch syntax, type "MSBuild -help"
rebuild: clean: Failed! The command exited with code 1. (1.25 s)
rebuild: ───────────────────────────────
rebuild: Target  Outcome  Duration
rebuild: ──────  ───────  ──────────────
rebuild: clean   Failed!  1.25 s  100,0%
rebuild: ───────────────────────────────
rebuild: Failed! (rebuild) (1.27 s)
PS C:\Users\diego.pozzi\OneDrive - MyCompanyName\Documenti\GitHub\PowerApps-Language-Tooling>

I suppose that I should find something under ...\PowerApps-Language-Tooling\obj\logs but the folder doesn't exist

**Comment by jt000** [comment]
Ah, I was able to reproduce. Looks like it's due to the space in the folder name. As a workaround, can you move it to a folder without spaces in the name?

**Comment by tomjschneider** [comment]
This fix only impacts the local build of this project, so it is now available and does not need to wait on a release.
