### ISSUE TITLE
Fail to unpack any app that contains more than one AIModel control

### ISSUE THREAD

**Issue by mandinger** [microsoft/PowerApps-Language-Tooling#447]
**Describe the bug**
Trying to unpack any canvas app containing 2 or more AiModels controls fails with the PA2001 and PA3015 errors

Failed to unpack solution using PASopa V0.24

**To Reproduce**

1. Unpacking any solution with 2 or more AIModel controls

[errorLog.txt](https://github.com/microsoft/PowerApps-Language-Tooling/files/9826299/errorLog.txt)

[asd.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/9826302/asd.zip)

**Comment by tomjschneider** [comment]
Thanks for the example app @mandinger. I'll get this to the team for investigation.
