### ISSUE TITLE
Issue building on Mac

### ISSUE THREAD

**Issue by alexandrebakercode** [microsoft/PowerApps-Language-Tooling#448]
I am trying to run the ./build and the ./buld ci and get the following error

$ ./build
rebuild: Starting... (rebuild)
rebuild: clean: Starting...
targets: dotnet clean /Users/Alex/Power Platform Tools/PowerApps-Language-Tooling/src/PASopa.sln --configuration Debug /clp:verbosity=minimal /flp:Verbosity=normal;LogFile=/Users/Alex/Power Platform Tools/PowerApps-Language-Tooling/obj/logs/clean-Debug.log /flp3:PerformanceSummary;Verbosity=diag;LogFile=/Users/Alex/Power Platform Tools/PowerApps-Language-Tooling/obj/logs/clean-Debug.diagnostics.log -p:GitExists=true /nologo
MSBUILD : error MSB1008: Only one project can be specified.
Switch: Platform

For switch syntax, type "MSBuild -help"
rebuild: clean: Failed! The command exited with code 1. (840 ms)
rebuild: ───────────────────────────────
rebuild: Target  Outcome  Duration      
rebuild: ──────  ───────  ──────────────
rebuild: clean   Failed!  840 ms  100.0%
rebuild: ───────────────────────────────
rebuild: Failed! (rebuild) (858 ms)

**Comment by tomjschneider** [comment]
Hey @alexandrebakercode , we're aware of an issue when building at a path that contains spaces (see https://github.com/microsoft/PowerApps-Language-Tooling/issues/443). It looks like you may be hitting the same issue. Can you try running build from a location which does not have spaces in the folder name and let me know if that works?

**Comment by tomjschneider** [comment]
Closing as a duplicated for #443. Feel free to re-open if you feel otherwise, or a path name with no spaces does not resolve your issue.
