### ISSUE TITLE
Solution Canvas app support

### ISSUE THREAD

**Issue by JonKragh** [microsoft/PowerApps-Language-Tooling#462]
Hi - great tool. I'm not sure who to reach out to for discussion, so apologize for this issue.

Use Case:

We want to have multiple versions of the same canvas app in a solution and then use power apps unpack/pac to merge.

For example:
- MainApp
- MainAppVnext
- MainAppOtherFeature

Do you know if the solution has other metadata we also need to merge?

At a fundamental level, should using the canvas app unpack and pac work across multiple canvas apps?

Thanks!
Jon

**Comment by clairewu0218** [comment]
Hi Jon,

Pac/unpack is for `.msapp` files and don't support solutions at this time. We don't know the answer about solution metadata. One way you can try is to pac/unpack the different versions of apps respectively, then merge them manually or with some version control tools.

Hope it helps.

Best,
Claire

**Comment by tomjschneider** [comment]
Hey @JonKragh - I'd recommend checking out the `solution` verb available in the Power Platform CLI: https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/solution

You may be able to use the `solution unpack` command to accomplish this.

**Comment by JonKragh** [comment]
@tomjschneider @clairewu0218 we actually now have pac/unpack for the canvas apps working in conjunction with solutions. I think we may be doing some unique ALM things now with branching/merging apps similar to typical prodev workflows.
