### ISSUE TITLE
Any application that was created using "Customize Forms" in the list is not unpacked correctly.

### ISSUE THREAD

**Issue by oktirus** [microsoft/PowerApps-Language-Tooling#470]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain s
[testUnzip on Test forms.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/11422137/testUnzip.on.Test.forms.zip)
ensitive personal or company data.)*

**Describe the bug**

Any application that was created using "Customize Forms" in the list is not unpacked correctly(Old ot New).
About a week ago, everything was working correctly. During unpacking, a folder "diffFiles" appears with two files, they contain only one difference "HostType": "SharepointForms", → "HostType": "Default".
Also I am getting the following errors:
FAIL: hash mismatch: Controls\1.json
Warning PA2001: Checksum mismatch. File Controls\1.json checksum does not match on extract
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Error   PA3013: Property Value Changed: TopParent.Children[1].Template.HostType
Error   PA3011: Roundtrip validation on unpack failed.

**To Reproduce**

I use the command: 
pasopa.exe -unpack (FileName.msapp) (PathUnpackFolder)

**Screenshots**

![image](https://user-images.githubusercontent.com/17222585/236860604-c9f15430-6d76-4897-a4dd-84167861caa8.png)

If you make changes and package, the following error occurs during import and the application will not start.

![image](https://user-images.githubusercontent.com/17222585/236861145-b9a9e040-df60-4ff6-885b-510d705f59ad.png)

**Comment by NavneetThekkumpat** [comment]
This has been resolved that in this library (linked PR solves this issue for this standalone tool). 
Closing this issue, please feel to reopen if the issue persists.
