### ISSUE TITLE
PA3015: TopParent.Children[1].Template.HostService.Name Failure

### ISSUE THREAD

**Issue by R4isin** [microsoft/PowerApps-Language-Tooling#471]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**

Unable to unpack an msapp file when 
- using the Power Platform tools in Visual Studio Code 
Or 
- using the pipeline "export-solution-to-git" via "ALM Accelerator"

**To Reproduce**

Ran this command
pac canvas unpack --msapp xxxx.msapp --sources .\src 
Or 
Ran the pipeline "export-solution-to-git" via ALM Accelerator"

**Screenshots**

PS E:\Downloads\Testunpack_20230509085042\Microsoft.PowerApps\apps\15970322999855747459> pac canvas unpack --msapp "Nde6bcfc2-affe-4235-bab7-6f908b933315-document.msapp" --sources src
Warning: canvas unpack is in preview, and functionality is not guaranteed. Use extreme caution if using in a production environment. For more information see https://aka.ms/paccanvas
Unpack from E:\Downloads\Testunpack_20230509085042\Microsoft.PowerApps\apps\15970322999855747459\Nde6bcfc2-affe-4235-bab7-6f908b933315-document.msapp --> E:\Downloads\Testunpack_20230509085042\Microsoft.PowerApps\apps\15970322999855747459\src
  source format version: 0.24
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Microsoft PowerPlatform CLI
Version: 1.22.4+gfad5a46

Error: Error   PA3015: Property Removed: TopParent.Children[1].Template.HostService.Name
Error   PA3015: Property Removed: TopParent.Children[1].Template.HostService.ServiceKind
Error   PA3015: Property Removed: TopParent.Children[1].Template.HostService.Type
Error   PA3015: Property Removed: TopParent.Children[1].Template.HostService.WadlMetadata.WadlXml
Error   PA3013: Property Value Changed: TopParent.Children[1].Template.HostType
Error   PA3011: Roundtrip validation on unpack failed.
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling

**Additional context**

I tried to follow the solution explained on this page but I don't really understand (https://github.com/microsoft/PowerApps-Language-Tooling/blob/master/docs/KnownIssues.md#error-pa3013-property-value-changed-topparentallowaccesstoglobals-or-similar). I opened my canvas app in Power Apps Studio from the msapp file. Once done, I don't know how to select/find my affected component since I have no idea what is linked to TopParent.Children[1].Template.HostService.Name.

**Comment by landonarogers** [comment]
Hey, R4isin! Thank you for filing this issue. Do you have an msapp that you can share with us, that has the issue? You can also send it to my email: landonrogers at microsoft dot com :)

**Comment by R4isin** [comment]
Done by mail. Thanks for your help :)
