### ISSUE TITLE
Multiple errors in PAC CLI with ALM Accelerator deplyoments

### ISSUE THREAD

**Issue by tomjosbin** [microsoft/PowerApps-Language-Tooling#472]
Getting the below set of errors while using ALM Accelerator for a deployment. The deployment goes well for manual export & import. 

Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Microsoft PowerPlatform CLI
Version: 1.22.3+g8af83fd

Error: Error   PA3013: Property Value Changed: TopParent.Children[1].Template.HostType
Error   PA3011: Roundtrip validation on unpack failed. 
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling

    Error   PA3013: Property Value Changed: TopParent.Children[1].Template.HostType
Error   PA3011: Roundtrip validation on unpack failed. 
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling

**Comment by tomjosbin** [comment]
Hello @NavneetThekkumpat, could you please let me know when we can expect the release with this fix ?

**Comment by NavneetThekkumpat** [comment]
@tomjosbin  The latest version of the PAC CLI has been released with the fix. If you are still experiencing roundtripping errors on the latest version of the CLI, please feel free to reopen this issue.
