### ISSUE TITLE
'pac solution clone' failing with 'PA3015: Property Removed' error 

### ISSUE THREAD

**Issue by RajeevPentyala** [microsoft/PowerApps-Language-Tooling#479]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**

I've a 'Dataverse' solution with a 'Page' component. While cloning the solution using 'pac solution clone' command, getting following error.

_Error: Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.dataSources.environment_39a902ba.entitySetName
Error   PA3015: Property Removed: LocalDatabaseReferences.default.cds.dataSources.environment_39a902ba.logicalName
Error   PA3011: Roundtrip validation on unpack failed._

**To Reproduce**

Clone the solution using 'pac solution clone' command.

**Screenshots**

![image](https://github.com/microsoft/PowerApps-Language-Tooling/assets/104883923/2ab02227-c529-4db9-b16e-f2b12b79930b)

**Additional context**

Solution has a 'page' component.

**Comment by akshar2401** [comment]
Pr linked with this issue got merged recently and would ultimately fix this issue. The fix should be shipped in the next release of PAC CLI
