### ISSUE TITLE
Error: Error   PA3015: Property Removed: TopParent.Children[1].Template.HostService.Name

### ISSUE THREAD

**Issue by mjchilenski** [microsoft/PowerApps-Language-Tooling#481]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**

Error using Power Platform ALM Accelerator pac-Clone or Sync Solution step

**To Reproduce**

1. Checksum mismatch unpacking canvas app

**Screenshots**

![image](https://github.com/microsoft/PowerApps-Language-Tooling/assets/82622604/dcce4a36-d55e-4d10-9e2e-1ca49fbfd9b8)

**Additional context**

Add any helpful context on the .msapp like created from teams, contains custom pcf components, etc.
![ALMError](https://github.com/microsoft/PowerApps-Language-Tooling/assets/82622604/f70f8706-c0dd-4fc4-8a62-bbec7286a158)

**Comment by NavneetThekkumpat** [comment]
The latest version of the PAC CLI has been released with the fix. If you are still experiencing roundtripping errors on the latest version of the CLI, please feel free to reopen this issue.

**Comment by akshar2401** [comment]
Pr linked with the issue would ultimately fix this issue and other similar issues filed around the same time as this one. The fix should be in the next release of PAC CLI
