### ISSUE TITLE
Unpack failed

### ISSUE THREAD

**Issue by mitch2300** [microsoft/PowerApps-Language-Tooling#490]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)* Tried to attached msapp file but got error indicated that file type is not supported

Unpack failed.  Used "pac canvas unpack --msapp "entities.msapp" --sources src" as CLI command

Text of error returned is below. Note last two lines below. (Note that I have only pasted partial text of error received since original attempt to paste entire error generated an error that text was too long.)

Error   PA3015: Property Removed: TopParent.Children[0].Template.ComponentDefinitionInfo.Children[1].Children[1].Children[4].Children[1].Template.DynamicControlDefinitionJson.AuthConfigProperties[0].DisabledBorderColor.SectionName
Error   PA3015: Property Removed: TopParent.Children[0].Template.ComponentDefinitionInfo.Children[1].Children[1].Children[4].Children[1].Template.DynamicControlDefinitionJson.AuthConfigProperties[0].DisabledBorderColor.Type
Error   PA3015: Property Removed: TopParent.Children[0].Template.ComponentDefinitionInfo.Children[1].Children[1].Children[4].Children[1].Template.DynamicControlDefinitionJson.AuthConfigProperties[0].DisabledBorderColor.WizardStep
Error   PA3015: Property Removed: TopParent.Children[0].Template.ComponentDefinitionInfo.Children[1].Children[1].Children[4].Children[1].Template.DynamicControlDefinitionJson.AuthConfigProperties[0].DisabledFillColor.EnabledForFlyout
Error   PA3015: Property Removed: TopParent.Children[0].Template.ComponentDefinitionInfo.Children[1].Children[1].Children[4].Children[1].Template.DynamicControlDefinitionJson.Resources[54].Path
Error   PA3013: Property Value Changed: TopParent.Children[0].Template.ComponentDefinitionInfo.Children[1].Children[1].Children[4].Children[1].Template.DynamicControlDefinitionJson.Resources[55].Path
Error   PA3013: Property Value Changed: TopParent.Children[0].Template.ComponentDefinitionInfo.Children[1].Children[1].Children[4].Children[1].Template.DynamicControlDefinitionJson.Resources[56].Path
Error   PA3011: Roundtrip validation on unpack failed.
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling

**Comment by clairewu0218** [comment]
Could you share the msapp for us to retro the issue? It would be very helpful.
