### ISSUE TITLE
Responsive containers have extra default properties. 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Language-Tooling#76]
Adding a responsive container pulls in some extra default properties. 

![image](https://user-images.githubusercontent.com/1538900/102254143-237bf780-3ebd-11eb-9a18-4d9585dc5544.png)

**Comment by lesaltzm** [comment]
Unfortunately the group container .oam.xml is not included in the msapp template files currently. This will need to be addressed on the server before anything can be done here.

**Comment by lesaltzm** [comment]
item added to #21 to track.

**Comment by MikeStall** [comment]
Can we special case this on the client, so that we at least get the right format now? And then remove the special casing when we get the server update?

**Comment by lesaltzm** [comment]
Yes, we definitely can.
