### ISSUE TITLE
Review file format 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Language-Tooling#97]
Review the  file format to ensure it plays well with source control and Pull Request merging. Ensure each *Directory* falls into the following category, where all files in the directory have the same rules:

| # | Kind | Details | Examples |
| ---| --- | --- | ---  |
| 1 |  Source | file should be checked in | pa.yaml  |
| 2 | cache | file (in-theory) can be recreated, Still require checking in for now, but future version may have offline recovery. In theory, server could recover if missing | packages, ApiDef/Swagger  |
| 3 | optional | file can be safely deleted.  | editorstate.json,  |
| 4 | config | org-specific data. | Connections |

**Comment by MikeStall** [comment]
Key file format updates made with #140
We may have a candidate for final format.

**Comment by landonarogers** [comment]
@MikeStall Is this issue still in progress?
